// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReportProvider } from "@/context/ReportContext"; // Provider ยังคงต้องครอบทั้งหมด

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SOC System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReportProvider>
            {/* ลบ Sidebar และ div จัดหน้าออก ให้เหลือแค่นี้ */}
            {children}
        </ReportProvider>
      </body>
    </html>
  );
}