// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar"; // 1. Import Sidebar มา

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SOC Daily Report",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {/* สร้าง Container หลักเป็น Flexbox */}
        <div className="flex min-h-screen bg-gray-100">
          
          {/* ส่วนซ้าย: Sidebar (จะซ่อนตัวเองอัตโนมัติเมื่อสั่ง Print) */}
          <Sidebar />

          {/* ส่วนขวา: เนื้อหา (A4) */}
          <main className="flex-1 h-screen overflow-y-auto p-8 print:p-0 print:h-auto print:overflow-visible">
            {children}
          </main>

        </div>
        
      </body>
    </html>
  );
}